import Header from './Header';

const menuData = {
  data: {
    menuItems: {
      nodes: [
        {
          key: 'cG9zdDoyNzg=',
          parentId: null,
          title: 'Home',
          url: '/',
          path: '/',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: null,
          },
        },

        {
          key: 'cG9zdDh9',
          parentId: null,
          title: 'Industries',
          url: '#',
          path: '#',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: true,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MzZd',
          parentId: 'cG9zdDh9',
          title: 'Energy',
          url: '/industries/energy/',
          path: '/industries/energy/',
          description: 'Real time (Sensor) Data Analytics Solutions',
          menuAcfFields: {
            showMenuLabel: true,
            menuLabelText: 'New',
            showMegaMenu: true,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/05/sensor-icon-icon.svg',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo4',
          parentId: null,
          title: 'Services',
          url: '#',
          path: '#',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: true,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: 'New',
          },
        },
        {
          key: 'cG9zdDoyMTU=',
          parentId: 'cG9zdDo4',
          title: 'Artificial Intelligence',
          url: '/services/artificial-intelligence/',
          path: '/services/artificial-intelligence/',
          description:
            'Lorem Ipsum is simply dummy text of the printing and typesetting',
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3Mzg4',
          parentId: 'cG9zdDoyMTU=',
          title: 'AI/ML Ops',
          url: '/services/artificial-intelligence/ai-ml-ops/',
          path: '/services/artificial-intelligence/ai-ml-ops/',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/recomnd_eng_icon_icon.png',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3Mzg5',
          parentId: 'cG9zdDoyMTU=',
          title: 'AI Deep Learning',
          url: '/services/artificial-intelligence/ai-deep-learning/',
          path: '/services/artificial-intelligence/ai-deep-learning/',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/neural-network_icon_icon1.png',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3Mzkw',
          parentId: 'cG9zdDoyMTU=',
          title: 'Machine Learning and Predictive Analytics',
          url: '/services/artificial-intelligence/ml-predictive-analytics/',
          path: '/services/artificial-intelligence/ml-predictive-analytics/',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/system_ml_icon_icon.png',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3Mzk1',
          parentId: 'cG9zdDoyMTU=',
          title: 'Recommendation Engine',
          url: '/services/artificial-intelligence/recommendation-engines/',
          path: '/services/artificial-intelligence/recommendation-engines/',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/gen_ai_con_icon.png',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3Nzg2',
          parentId: 'cG9zdDoyMTU=',
          title: 'Gen AI',
          url: '/genai',
          path: '/genai',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2025/01/gen-ai-chip.svg',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDoyMTQ=',
          parentId: 'cG9zdDo4',
          title: 'Data Analytics',
          url: '/services/data-analytics/',
          path: '/services/data-analytics/',
          description:
            'Lorem Ipsum is simply dummy text of the printing and typesetting',
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: '-100',
            menuIcon: null,
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MjQz',
          parentId: 'cG9zdDoyMTQ=',
          title: 'Cloud Computing',
          url: '#',
          path: '#',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MjQ0',
          parentId: 'cG9zdDoyMTQ=',
          title: 'Analytics & BI',
          url: '#',
          path: '#',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MjQ1',
          parentId: 'cG9zdDoyMTQ=',
          title: 'Master Data Management',
          url: '#',
          path: '#',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MjQ2',
          parentId: 'cG9zdDoyMTQ=',
          title: 'Data Lake & DWH',
          url: '#',
          path: '#',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MjQ3',
          parentId: 'cG9zdDoyMTQ=',
          title: 'Big Data',
          url: '#',
          path: '#',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MjQ4',
          parentId: 'cG9zdDoyMTQ=',
          title: 'Cloud Ops',
          url: '#',
          path: '#',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDoyMTM=',
          parentId: 'cG9zdDo4',
          title: 'Enterprise Applications',
          url: '/services/enterprise-applications/',
          path: '/services/enterprise-applications/',
          description:
            'Lorem Ipsum is simply dummy text of the printing and typesetting',
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: '-200',
            menuIcon: null,
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MjUx',
          parentId: 'cG9zdDoyMTM=',
          title: 'Oracle Fusion & EBS',
          url: '#',
          path: '#',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MjUy',
          parentId: 'cG9zdDoyMTM=',
          title: 'SAP',
          url: '/',
          path: '/',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MjUz',
          parentId: 'cG9zdDoyMTM=',
          title: 'Custom Web & Mobile Development',
          url: '/',
          path: '/',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo5',
          parentId: null,
          title: 'Solutions',
          url: '#',
          path: '#',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: true,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MzQy',
          parentId: 'cG9zdDo5',
          title: 'Kafka',
          url: '/solutions/real-time-sensor-data-analytics-solutions/',
          path: '/solutions/real-time-sensor-data-analytics-solutions/',
          description: 'Real time (Sensor) Data Analytics Solutions',
          menuAcfFields: {
            showMenuLabel: true,
            menuLabelText: 'New',
            showMegaMenu: true,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/05/sensor-icon-icon.svg',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MzQz',
          parentId: 'cG9zdDo5',
          title: 'Microsoft',
          url: '/solutions/microsoft-fabric-solutions/',
          path: '/solutions/microsoft-fabric-solutions/',
          description: 'Microsoft Fabric Solutions',
          menuAcfFields: {
            showMenuLabel: true,
            menuLabelText: 'Exclusive',
            showMegaMenu: null,
            showServicesMegaMenu: true,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/ms_fabric_menu_icon_icon.svg',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MzQ1',
          parentId: 'cG9zdDo5',
          title: 'ChatGPT',
          url: '/solutions/enterprise-chatgpt-solutions/',
          path: '/solutions/enterprise-chatgpt-solutions/',
          description: 'Enterprise ChatGPT Solutions',
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/chatgpt_menu_icon_icon.svg',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MzQ2',
          parentId: 'cG9zdDo5',
          title: 'Spotfire',
          url: '/solutions/spotfire-to-power-bi-migration-solution/',
          path: '/solutions/spotfire-to-power-bi-migration-solution/',
          description: 'Spotfire to Power BI Migration Solution',
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/spotfire_menu_icon_icon.svg',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MzQ3',
          parentId: 'cG9zdDo5',
          title: 'Power BI',
          url: '/solutions/rls-power-app-offer/',
          path: '/solutions/rls-power-app-offer/',
          description: 'Power BI Security Utility Application',
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/powerbi_menu_icon_icon.svg',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MzQ4',
          parentId: 'cG9zdDo5',
          title: 'Salesforce',
          url: '/solutions/salesforce-utility-for-data-ingestion/',
          path: '/solutions/salesforce-utility-for-data-ingestion/',
          description: 'Salesforce Utility for Data Ingestion',
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/salesforce_menu_icon_icon.svg',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MzQ5',
          parentId: 'cG9zdDo5',
          title: 'Analytics',
          url: '/solutions/power-bi-usage-metrics/',
          path: '/solutions/power-bi-usage-metrics/',
          description: 'Power BI Consumption Analytics/Usage Metrics',
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/powerbi_menu_icon_icon.svg',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MzUx',
          parentId: 'cG9zdDo5',
          title: 'Hadoop',
          url: '/solutions/hadoop-to-azure-migration/',
          path: '/solutions/hadoop-to-azure-migration/',
          description: 'Hadoop migration to Azure: 6-Wk Proof of Concept',
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/hadoop_menu_icon_icon.svg',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MzQ0',
          parentId: 'cG9zdDo5',
          title: 'SharePoint',
          url: '/solutions/mvp-sharepoint-to-adls-data-migration-and-access-permissions-matching/',
          path: '/solutions/mvp-sharepoint-to-adls-data-migration-and-access-permissions-matching/',
          description:
            'MVP: SharePoint to ADLS Data Migration and Access Permissions Matching',
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/sharepoint_menu_icon_icon.svg',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MzUy',
          parentId: 'cG9zdDo5',
          title: 'Oracle',
          url: '/solutions/oracle-fusion-free-workshop/',
          path: '/solutions/oracle-fusion-free-workshop/',
          description:
            'Free Workshop: Connecting Oracle Fusion/ Cloud ERP Application with Power BI',
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/oracle_menu_icon_icon.svg',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3MjQ5',
          parentId: null,
          title: 'Resources',
          url: '#',
          path: '#',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: null,
          },
        },

        {
          key: 'cG8zdCoyIzK=',
          parentId: 'cG9zdDo3MjQ5',
          title: 'Life At Bizmetric',
          url: '/life-at-bizmetric',
          path: '/life-at-bizmetric',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/about_us_info_icon_icon.png',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDoyMzM=',
          parentId: 'cG9zdDo3MjQ5',
          title: 'About Us',
          url: '/about-us',
          path: '/about-us',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/about_us_info_icon_icon.png',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3Mjgy',
          parentId: 'cG9zdDo3MjQ5',
          title: 'Newsletters',
          url: '/newsletters',
          path: '/newsletters',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/newsletter_menu_icon_icon.svg',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDo3Njk2',
          parentId: 'cG9zdDo3MjQ5',
          title: 'Careers',
          url: '/careers',
          path: '/careers',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/career_menu_icon_icon1.svg',
            },
            menuLabel098: null,
          },
        },
        // {
        //   key: 'cG9zdDo3Mjg0',
        //   parentId: 'cG9zdDo3MjQ5',
        //   title: 'E-Books',
        //   url: '/',
        //   path: '/',
        //   description: null,
        //   menuAcfFields: {
        //     showMenuLabel: null,
        //     menuLabelText: null,
        //     showMegaMenu: null,
        //     showServicesMegaMenu: null,
        //     menuClasses: null,
        //     menuIcon: {
        //       mediaItemUrl:
        //         'https://experimentalapp.xyz/wp-content/uploads/2024/04/ebook_menu_icon_icon.svg',
        //     },
        //     menuLabel098: null,
        //   },
        // },
        {
          key: 'cG9zdDo3NTQy',
          parentId: 'cG9zdDo3MjQ5',
          title: 'Blogs',
          url: '/blogs',
          path: '/blogs',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/blog_icon_icon.png',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDoyNDc=',
          parentId: 'cG9zdDo3MjQ5',
          title: 'Contact Us',
          url: '/contact-us',
          path: '/contact-us',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: {
              mediaItemUrl:
                'https://experimentalapp.xyz/wp-content/uploads/2024/04/contactus_icon_icon.png',
            },
            menuLabel098: null,
          },
        },
        {
          key: 'cG9zdDoxMA==',
          parentId: null,
          title: 'Success Stories',
          url: '/success-stories',
          path: '/success-stories',
          description: null,
          menuAcfFields: {
            showMenuLabel: null,
            menuLabelText: null,
            showMegaMenu: null,
            showServicesMegaMenu: null,
            menuClasses: null,
            menuIcon: null,
            menuLabel098: null,
          },
        },
      ],
    },
  },
};

export default function HeaderServer() {
  return <Header menus={menuData.data.menuItems} />;
}
